rules:
  type:
    level: error
    options:
      - feat
      - fix
      - chore
      - docs
      - test
      - style
      - perf

  subject-empty:
    level: error

  description-empty:
    level: error

  description-max-length:
    level: error
    length: 80

  #description-format:
  #  level: error
  #  format: ^..todo..$

  body-empty:
    level: ignore
  
  footers-empty:
    level: ignore