[workspace]
members = [ "benchmarks", "book","intervalsets", "intervalsets-core"]
default-members = ["intervalsets", "intervalsets-core"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.2"
authors = ["Greg Echelberger"]
edition = "2021"
rust-version = "1.81.0"
homepage = "https://gechelberger.github.io/intervalsets/"
repository = "https://github.com/gechelberger/intervalsets"
license = "MIT"