[package]
name = "intervalsets"
version = "0.1.0-alpha.2"
authors = ["Greg Echelberger"]
edition = "2021"
rust-version = "1.65.0"
readme = "README.md"
description = """
The intervalsets crate provides bounded and unbounded intervals 
implemented as sets with all the associated set operations.
"""
repository = "https://github.com/gechelberger/intervalsets"
license = "MIT"
keywords = [
    "interval",
    "math",
    "set",
    "measure",
    "bound"
]
categories = ["mathematics", "science", "data-structures"]
exclude = ["notes/", "fuzz/"]

[dependencies]
chrono = { version = "0.4.38", optional = true }
itertools = "0.13.0"
num-bigint = { version = "0.4.6", optional = true }
num-traits = "0.2.19"
rust_decimal = { version = "1.36.0", optional = true }
uom = { version = "0.36.0", optional = true }

[dev-dependencies]
approx = "0.5.1"
husky-rs = "0.1.1"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[features]
rust_decimal = ["dep:rust_decimal"]
num-bigint = ["dep:num-bigint"]
chrono = ["dep:chrono"]
uom = ["dep:uom"]
