[package]
name = "intervalsets"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
rust_decimal = { version = "1.36.0", optional = true }
thiserror = "1.0.64"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[features]
decimal = ["rust_decimal"]