[package]
name = "intervalsets"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
itertools = "0.13.0"
num-bigint = { version = "0.4.6", optional = true }
num-integer = { version = "0.1.46", optional = true }
num-rational = { version = "0.4.2", optional = true }
num-traits = "0.2.19"
rust_decimal = { version = "1.36.0", optional = true }
thiserror = "1.0.64"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[features]
rust_decimal = ["dep:rust_decimal"]
num-bigint = ["dep:num-bigint"]
num-rational = ["dep:num-rational", "dep:num-integer"]
