[package]
name = "intervalsets-core"
version = "0.1.0-alpha.2"
edition = "2021"

[dependencies]
const_env = "0.1.2"
heapless = "0.8.0"
itertools = { version = "0.13.0", default-features = false }
laxcow = "0.2.0"
nom = { version = "7.1.3", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
ordered-float = { version = "4.5.0", default-features = false }
tinyvec = { version = "1.8.0", default-features = false }
