#!/bin/sh

# This script is derived from 
# [cargo-hook](https://github.com/jackos/cargo-hook),
# whiche, at the time of this writing, is realesed without
# any license information.

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

echo "---------------------------"
echo "- ✨  Running clippy   ✨ -"
echo "---------------------------"
cargo clippy -- -Dwarnings
LINTER_EXIT_CODE=$?

if [ $LINTER_EXIT_CODE -ne 0 ]; then
    echo "---------------------------"
    echo "- ❌ Fix clippy errors ❌ -"
    echo "---------------------------"

    exit 1
else
    echo "✅"
fi

echo "---------------------------"
echo "- ✨ Running formatter ✨ -"
echo "---------------------------"
cargo fmt
echo "✅"

git add -f $STAGED_FILES

echo "---------------------------"
echo "- ✨   Running tests   ✨ -"
echo "---------------------------"
cargo test --all-features
TEST_EXIT_CODE=$?

if [ $TEST_EXIT_CODE -ne 0 ]; then
    echo "---------------------------"
    echo "- ❌  Fix test errors  ❌ -"
    echo "---------------------------"
    exit 1
else
    echo "✅"
fi

echo "--------------------------------------"
echo "- 🎉 linted, formatted and tested 🎉 -"
echo "--------------------------------------"
exit 0