name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - run: cargo test --all-features --verbose

  no-std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install nightly toolchain with nostd target
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: thumbv6m-none-eabi
    - name: Install cargo hack
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-hack
        version: '^0.6'
    - name: install just
      uses: baptiste0928/cargo-install@v3
      with:
        crate: just
        version: '^1'
    - run: just check-no-std

  msrv-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "1.81.0"
    - run: cargo test --all-features --verbose

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo +nightly doc --all-features --no-deps
        env:
          RUSTDOCFLAGS: "-D warnings --cfg docsrs"