name: Rust

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-features --all-targets -- -D warnings

  no-std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install nightly toolchain with nostd target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv6m-none-eabi
      - name: Install cargo hack
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-hack
          version: "^0.6"
      - name: install just
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just
          version: "^1"
      - run: just check-no-std

  msrv-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.85.0"
      - run: cargo test --all-features --verbose

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - name: install just
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just
          version: "^1"
      - run: just doc
